name: release

on:
  release:
    types:
      - created

jobs:
  docker:
    name: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          build-args: VERSION=${{ github.event.release.tag_name }}
          tags: ghcr.io/scrin/ruuvi-go-gateway:${{ github.event.release.tag_name }}
  binaries:
    name: binaries
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        goarch: [amd64, arm64, arm]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build binary
        uses: wangyoucao577/go-release-action@v1.22
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: ${{ matrix.goarch }}
          goversion: 1.17
          ldflags: "-X github.com/Scrin/ruuvi-go-gateway/common/version.Version=${{ github.event.release.tag_name }}"
          project_path: ./cmd/ruuvi-go-gateway
          binary_name: ruuvi-go-gateway
          retry: 10
          md5sum: false
          overwrite: true
